controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_fr3_joint1
      - left_fr3_joint2
      - left_fr3_joint3
      - left_fr3_joint4
      - left_fr3_joint5
      - left_fr3_joint6
      - left_fr3_joint7
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_fr3_joint1
      - right_fr3_joint2
      - right_fr3_joint3
      - right_fr3_joint4
      - right_fr3_joint5
      - right_fr3_joint6
      - right_fr3_joint7
  - name: fake_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - left_fr3_finger_joint1
  - name: fake_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - right_fr3_finger_joint1
  - name: fake_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - left_fr3_finger_joint1
initial:
  - group: left_arm
    pose: ready
  - group: right_arm
    pose: ready
