controller_list:
  - name: /right_arm/effort_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - right_fr3_joint1
      - right_fr3_joint2
      - right_fr3_joint3
      - right_fr3_joint4
      - right_fr3_joint5
      - right_fr3_joint6
      - right_fr3_joint7
  - name: /left_arm/effort_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_fr3_joint1
      - left_fr3_joint2
      - left_fr3_joint3
      - left_fr3_joint4
      - left_fr3_joint5
      - left_fr3_joint6
      - left_fr3_joint7
  - name: /right_arm/franka_gripper
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - right_fr3_finger_joint1
      - right_fr3_finger_joint2
  - name: /left_arm/franka_gripper
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - left_fr3_finger_joint1
      - left_fr3_finger_joint2